site_name: Kubernetes Tutorial with CKA/CKAD Prep
site_url: http://kubernetes-tutorial.schoolofdevops.com/
site_author: Gourav Shah
site_description: Complete Kubernetes Tutorial by Example
google_analytics: ['UA-36802546-16', 'kubernetes-tutorial.schoolofdevops.com']
nav:
  - Home: "index.md"
  - Docker Essentials for Kubernetes:
     - Lab D101 - Operating Containers: "operating-docker-containers.md"
     - Lab D102 - Building and Publishing Docker Images: "building-publishing-docker-images.md"
     - Lab D103 - Docker Networking: "docker-networking.md"
     - Lab D104 - Docker Volumes: "docker-volumes.md"
  - Kubernetes Essentials for CKA/CKAD:
     - Lab K101 - Install Kubernetes with KIND: "kind_create_cluster.md"
     - Lab K102 - Kubernetes Quickdive: "kubernetes_quickdive.md"
     - Lab K103 - Pods: "create-and-deploy-kubernetes-pods.md"
     - Lab K104 - Namespaces and ReplicaSets: "kubernetes-replicasets-howto.md"
     - Lab K105 - Service Networking: "kubernetes-service-networking.md"
     - Lab K107 - Deployments: "kubernetes-rollouts-rollbacks-deployments.md"
     - Lab K108 - Storage: "kubernetes-dynamic-storage-provisioning.md"
     - Lab K109 - Mini Project: "kubernetes-sample-project.md"
     - Lab K110 - ConfigMaps & Secrets: "kubernetes-configuration-management-configmaps-secrets.md"
     - Lab K112 - Ingress: "ingress.md"
     - Lab K113 - HELM Package Manager: "helm.md"
     - Lab K114 - Writing HELM Charts: "helm_charts.md"
     - Lab K115 - Publishing HELM Charts: "helm_charts_publish.md"
  - Additional CKAD Topics:
     - Lab K201 - Advanced Pod Design: "advanced_pod_design.md"
     - Lab K204 - Health Checks: "pods-health-probes.md"
     - Lab K205 - DaemonsSets & CronJobs: "daemonsets_cronsjobs.md"
     - Lab K206 - Statefulsets: "13_redis_statefulset.md"
  - Additional CKA Topics:
     - Lab K301 - Auto Scaling with HPA : "10_kubernetes_autoscaling.md"
     - Lab K302 - Autoscaling on Custom Metric: "custom_autoscaling.md"
     - Lab K303 - Advanced Pod Scheduling: "advanced_pod_scheduling.md"
     - Lab K304 - Cluster Administration: "cluster-administration.md"
     - Lab K305 - Cluster Troubleshooting: "cluster-troubleshooting.md"
  - Kubernetes Security:
     - Lab K111 - RBAC Policies: "rbac_101.md"
     - Lab K207 - Network Policies: "network_policies.md"
  - Additional Topics:
     - Lab K400 - Install Kubernetes with Kubeadm: "install_kubernetes_with_kubeadm.md"
     - Lab K401 - Creating Users, Groups and Authorization: "configuring_authentication_and_authorization.md"
     - Lab K403 - Building Deployment Strategies: "vote-deployement_strategies.md"
     - Lab K404 - CNI: "cni.md"
     - Lab K404 - Kubernetes Operators: "operator.md"
     - Troubleshooting Tips: "12_troubleshooting.md"
     - Logging: "logging.md"
  - AWS and Kubernetes:
     - Lab K405 - AWS Controller for Kubernetes: "aws_ack_demo.md"
  - AWS EKS:
     - Lab K501 - EKS Preparatory Setup: "eks_prep.md"
     - Lab K502 - EKS Setup: "eks_setup.md"
     - Lab K503 - Deploy Apps on EKS: "eks_deploy_apps.md"
     - Lab K504 - Ingress with ALB: "eks_ingress_alb.md"
     - Lab K505 - Persistent Storage with EBS: "eks_storage.md"
     - Lab K506 - IRSA: "eks_irsa.md"
     - Lab K507 - EKS Cluster Autoscaler: "eks_cluster_autoscaler.md"
     - Lab K509 - Verticle Pod Autoscaler: "eks_vpa.md"
     - Lab K510 - EKS Monitoring: "eks_monitoring.md"
     - Lab K511 - EKS Costs: "eks_costs.md"
  - Exercises:
     - XER001 - Pods: "xer-001-pods.md"
     - XER002 - ReplicaSets: "xer-002-rs.md"
     - XER003 - Deploy Instavote Stack: "adv-k8s-project.md"
  - Web Quests:
     - KWQ001 - CNI Web Quest: "wq001-cni.md"
     - KWQ001 - Kubernetes Security Web Quest: "wq002-security.md"
     - KWQ003 - Ingress Web Quest: "wq003-ingress.md"
     - KWQ004 - Monitoring Web Quest: "wq004-monitoring.md"
     - KWQ005 - Controllers Web Quest: "wq005-controllers.md"
     - KWQ006 - Persistent Data Web Quest: "wq006-persistentvolume.md"
     - KWQ007 - Cluster Maintenance Web Quest: "wq007-maintenance.md"
  - References:
     - RBAC apiGroups to Resource Mapping: "rbac-resource-group-mapping.md"
docs_dir: chapters
theme: readthedocs
plugins:
    - search
repo_url: https://github.com/schoolofdevops/kubernetes-labguide
edit_uri: edit/master/chapters
copyright: Copyright @ 2017-2020 Gourav Shah, School of Devops. Some rights reserved. License CC BY-NC-SA
extra:
  social:
    - type: 'github'
      link: 'https://github.com/schoolofdevops'
    - type: 'twitter'
      link: 'https://twitter.com/gouravhah'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/gouravshah'
